language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -sc)/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update -q
  - sudo apt-get install r-base-dev

install:
  - pip install -r tests/requirements.txt

script:
  - pytest --tb=short -v

cache:
  pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
