language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -sc)/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update -q
  - sudo apt-get install r-base-dev
  - sudo apt-get install octave

install:
  - pip install -r tests/requirements.txt

before_script:
  - wget -P /home/travis https://sites.google.com/site/bctnet/Home/functions/BCT.zip
  - unzip /home/travis/BCT.zip -d /home/travis
  - export PATH=$PATH:/home/travis/BCT/
  - echo 'addpath(genpath("~/BCT"))' > /home/travis/.octaverc

script:
  - pytest --tb=short -v

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
  - $HOME/BCT
  - $HOME/.cache/pip
